In [44]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [45]:
df.shape

(2410, 5)

In [46]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [47]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [48]:
df[df.target_label=='System Notification'].sample(10)

,timestamp,source,log_message,target_label,complexity
1479,5/19/2025 21:28,ModernCRM,Backup started at 2025-07-26 10:56:51.,System Notification,regex
92,12/4/2025 21:20,BillingSystem,System reboot initiated by user User471.,System Notification,regex
598,9/9/2025 11:36,ModernHR,Disk cleanup completed successfully.,System Notification,regex
824,2/24/2025 2:57,AnalyticsEngine,Backup completed successfully.,System Notification,regex
1274,8/9/2025 17:23,ModernCRM,Backup ended at 2025-10-17 19:00:39.,System Notification,regex
1106,12/28/2025 13:32,ModernHR,System reboot initiated by user User246.,System Notification,regex
1586,5/2/2025 8:32,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex
2020,8/7/2025 9:03,ModernHR,File data_9413.csv uploaded successfully by us...,System Notification,regex
866,12/3/2025 4:16,ModernCRM,Backup completed successfully.,System Notification,regex
852,3/31/2025 5:20,ModernCRM,System reboot initiated by user User811.,System Notification,regex

In [49]:
df[df.log_message.str.startswith("System reboot initiated by user")]

,timestamp,source,log_message,target_label,complexity
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,regex
92,12/4/2025 21:20,BillingSystem,System reboot initiated by user User471.,System Notification,regex
139,5/8/2025 16:34,ModernHR,System reboot initiated by user User216.,System Notification,regex
140,9/11/2025 8:49,AnalyticsEngine,System reboot initiated by user User639.,System Notification,regex
161,3/31/2025 19:40,BillingSystem,System reboot initiated by user User819.,System Notification,regex
163,6/6/2025 15:29,BillingSystem,System reboot initiated by user User938.,System Notification,regex
307,4/12/2025 0:41,BillingSystem,System reboot initiated by user User929.,System Notification,regex
365,10/20/2025 22:32,ModernHR,System reboot initiated by user User533.,System Notification,regex
508,4/15/2025 2:04,ThirdPartyAPI,System reboot initiated by user User591.,System Notification,regex
552,9/22/2025 20:54,ModernHR,System reboot initiated by user User421.,System Notification,regex
668,9/5/2025 7:14,ModernHR,System reboot initiated by user User297.,System Notification,regex
693,7/6/2025 21:40,BillingSystem,System reboot initiated by user User159.,System Notification,regex
697,3/13/2025 7:09,BillingSystem,System reboot initiated by user User648.,System Notification,regex
714,9/25/2025 23:35,ThirdPartyAPI,System reboot initiated by user User600.,System Notification,regex
730,5/24/2025 11:08,AnalyticsEngine,System reboot initiated by user User120.,System Notification,regex
800,8/15/2025 12:14,BillingSystem,System reboot initiated by user User901.,System Notification,regex
837,4/9/2025 8:28,AnalyticsEngine,System reboot initiated by user User876.,System Notification,regex
852,3/31/2025 5:20,ModernCRM,System reboot initiated by user User811.,System Notification,regex
865,2/25/2025 1:40,AnalyticsEngine,System reboot initiated by user User964.,System Notification,regex
889,11/30/2025 13:45,ModernHR,System reboot initiated by user User766.,System Notification,regex
896,7/28/2025 11:24,BillingSystem,System reboot initiated by user User765.,System Notification,regex
988,9/11/2025 22:23,BillingSystem,System reboot initiated by user User427.,System Notification,regex
1106,12/28/2025 13:32,ModernHR,System reboot initiated by user User246.,System Notification,regex
1159,8/5/2025 6:52,BillingSystem,System reboot initiated by user User329.,System Notification,regex
1194,7/20/2025 9:10,AnalyticsEngine,System reboot initiated by user User747.,System Notification,regex
1275,7/15/2025 23:37,BillingSystem,System reboot initiated by user User829.,System Notification,regex
1299,7/15/2025 19:19,BillingSystem,System reboot initiated by user User966.,System Notification,regex
1304,8/10/2025 6:18,ThirdPartyAPI,System reboot initiated by user User758.,System Notification,regex
1524,11/30/2025 2:39,ThirdPartyAPI,System reboot initiated by user User278.,System Notification,regex
1562,8/18/2025 4:17,ThirdPartyAPI,System reboot initiated by user User648.,System Notification,regex
1624,12/14/2025 5:14,AnalyticsEngine,System reboot initiated by user User268.,System Notification,regex
1663,10/27/2025 22:04,AnalyticsEngine,System reboot initiated by user User315.,System Notification,regex
1776,2/21/2025 11:56,ModernHR,System reboot initiated by user User155.,System Notification,regex
1803,8/22/2025 6:30,AnalyticsEngine,System reboot initiated by user User204.,System Notification,regex
1804,8/26/2025 21:06,ModernHR,System reboot initiated by user User899.,System Notification,regex
1852,1/26/2025 12:34,AnalyticsEngine,System reboot initiated by user User223.,System Notification,regex
1865,5/11/2025 10:58,AnalyticsEngine,System reboot initiated by user User932.,System Notification,regex
1956,9/26/2025 19:32,ThirdPartyAPI,System reboot initiated by user User264.,System Notification,regex
2003,6/23/2025 17:54,ModernCRM,System reboot initiated by user User517.,System Notification,regex
2014,12/25/2025 4:33,AnalyticsEngine,System reboot initiated by user User293.,System Notification,regex
2043,9/12/2025 20:20,ThirdPartyAPI,System reboot initiated by user User262.,System Notification,regex
2074,9/13/2025 8:43,ModernCRM,System reboot initiated by user User937.,System Notification,regex
2228,9/3/2025 11:24,ModernHR,System reboot initiated by user User179.,System Notification,regex
2243,1/16/2025 7:22,ModernHR,System reboot initiated by user User770.,System Notification,regex
2246,3/2/2025 22:56,ModernHR,System reboot initiated by user User488.,System Notification,regex
2253,10/7/2025 2:20,ModernHR,System reboot initiated by user User644.,System Notification,regex
2317,3/7/2025 5:44,BillingSystem,System reboot initiated by user User724.,System Notification,regex
2360,5/1/2025 4:21,ThirdPartyAPI,System reboot initiated by user User876.,System Notification,regex

In [50]:
from sklearn.cluster import DBSCAN
from sentence_transformers import SentenceTransformer

In [51]:
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
embeddings = model.encode(df['log_message'].tolist())

In [52]:
embeddings[:5]

array([[-0.10293961,  0.03354594, -0.02202609, ...,  0.00457793,
        -0.04259719,  0.00322622],
       [ 0.00804576, -0.03573924,  0.0493874 , ...,  0.01538318,
        -0.06230947, -0.02774665],
       [-0.00908222,  0.13003924, -0.05275565, ...,  0.02014104,
        -0.05117099, -0.02930292],
       [-0.0975104 ,  0.049113  , -0.03977424, ...,  0.024775  ,
        -0.03546079, -0.00018601],
       [-0.10468334,  0.05926033, -0.02488502, ...,  0.0250205 ,
        -0.03719301, -0.02568913]], dtype=float32)

In [53]:
embeddings.shape

(2410, 384)

In [54]:
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clustering = dbscan.fit_predict(embeddings)
df['cluster'] = clustering

In [55]:
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [56]:
# Group by cluster to inspect patterns
clusters = df.groupby('cluster')['log_message'].apply(list)
sorted_clusters = clusters.sort_values(key=lambda x: x.map(len), ascending=False)

In [57]:
print("Clustered Patterns:")
for cluster_id, messages in sorted_clusters.items():
    if len(messages) > 10:
        print(f"Cluster {cluster_id}:")
        for msg in messages[:5]:
            print(f"  {msg}")

Clustered Patterns:
Cluster 0:
  nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
  nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
  nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
  nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
  nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369
Cluster 5:
  nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
  nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
  nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
  nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
  nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited
Cluster 11:
  User User685 logged out.
  User User395 logged in.
  User User225 logged in.
  User User494 logged out.
  User User900 logged in.
Cluster 13:
  Backup started at 2025-05-14 07:06:55.
  Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
  Backup started at 2025-11-14 08:27:43.
  Backup started at 2025-12-09 10:19:11.
Cluster 7:
  Multiple bad login attempts detected on user 8538 account
  Multiple login failures occurred on user 9052 account
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
  Multiple login failures were detected for user 6373
Cluster 8:
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
Cluster 21:
  System updated to version 3.9.1.
  System updated to version 5.5.4.
  System updated to version 4.7.4.
  System updated to version 3.7.7.
  System updated to version 2.6.2.
Cluster 3:
  Shard 6 replication task ended in failure
  Data replication task for shard 14 did not complete
  Data replication task failed for shard 17
  Replication of data to shard 14 failed
  Data replication task for shard 6 did not complete
Cluster 4:
  File data_6169.csv uploaded successfully by user User953.
  File data_3847.csv uploaded successfully by user User175.
  File data_7366.csv uploaded successfully by user User282.
  File data_1206.csv uploaded successfully by user User359.
  File data_1503.csv uploaded successfully by user User151.
Cluster 17:
  Denied access attempt on restricted account Account2682
  Unauthorized login attempt on protected account Account5030
  Account Account9437 blocked due to failed login
  Account Account7999 access denied due to login failure
  Invalid login attempt made on secured account Account7864
Cluster 32:
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
Cluster 6:
  Critical system unit error: unit ID Component55
  System component malfunction: component ID Component79
  Critical system element is down: element ID Component96
  Essential system part malfunction: part ID Component6
  Failure occurred in critical system component: component ID Component92
Cluster 16:
  System reboot initiated by user User243.
  System reboot initiated by user User471.
  System reboot initiated by user User216.
  System reboot initiated by user User639.
  System reboot initiated by user User819.
Cluster 20:
  User 7662 tried to bypass API security measures
  User 2367 failed to provide valid API access credentials
  User 3569 made an unauthorized API request
  Unauthorized user 2968 tried to access restricted API
  User 2186 attempted to access API without proper authorization
Cluster 9:
  Account with ID 5351 created by User634.
  Account with ID 7813 created by User373.
  Account with ID 9827 created by User965.
  Account with ID 2520 created by User546.
  Account with ID 2300 created by User964.
Cluster 1:
  Email service experiencing issues with sending
  Email server encountered a sending fault
  Mail service encountered a delivery glitch
  Service disruption caused by email sending error
  Email system had a problem sending emails
Cluster 10:
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
Cluster 34:
  Abnormal behavior found on server 10, possible security threat
  Security alert: suspicious activity on server 1
  Anomalous activity identified on server 23, security review recommended
  Server 27 experienced potential security incident, review required
  Server 36 experienced potential security incident, review required
Cluster 14:
  Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
  RAID array experienced multiple disk crashes
  Multiple hard drive issues in RAID configuration found
  Identification of multiple faulty disks in RAID array
Cluster 53:
  Module X experienced an invalid data format issue
  Input format mismatch occurred in module X
  Module X reported an error in input format validation
  Module X failed to process input due to formatting error
  Input data format in module X was invalid or corrupted
Cluster 52:
  Service health check was not successful because of SSL certificate validation failures.
  Invalid SSL certificate resulted in a failed service health check.
  Service health check failure was due to an invalid or improperly configured SSL certificate.
  An issue with the SSL certificate caused the service health check to fail.
  Service health check failure was caused by an expired SSL certificate.
Cluster 18:
  Boot process terminated unexpectedly due to kernel issue
  System encountered kernel panic during initialization phase
  Boot process was stopped by kernel malfunction
  System encountered kernel failure during bootup sequence
  Boot sequence failed due to kernel panic
Cluster 25:
  System configuration is no longer valid
  Configuration is corrupted throughout the system
  Cross-system configuration failure occurred
  System configuration is experiencing errors
  Configuration malfunction is system-wide
Cluster 42:
  User 5127 has escalated admin privileges without authorization
  User 9745 has escalated to admin level
  User 8483 escalated privileges to admin level
  User 1987 has escalated to admin level
  User 8395 escalated privileges to admin level
Cluster 59:
  Potential security threat: Admin privilege escalation for user 5130
  Admin privilege escalation alert for user 2893
  Admin privilege escalation alert for user 8532
  Potential security threat: Admin privilege escalation for user 1554
  Warning: Potential admin privilege escalation for user 5720
Cluster 26:
  Privilege elevation detected for user 5038
  Elevation of admin privileges detected for user 6137
  Elevation of admin privileges detected for user 4907
  User 6069 has been granted elevated admin privileges
  Admin privilege elevation warning for user 7574

In [58]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [59]:
classify_with_regex("User User123 logged in.")

'User Action'

In [60]:
classify_with_regex("System reboot initiated by user User179.")

'System Notification'

In [61]:
classify_with_regex("Hey you, chill bro")

In [62]:
# Apply regex classification
df['regex_label'] = df['log_message'].apply(lambda x: classify_with_regex(x))
df[df['regex_label'].notnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,regex,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,regex,11,User Action
...,...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,21,System Notification
2381,9/5/2025 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2394,4/3/2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2395,5/2/2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,regex,13,System Notification
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification

In [63]:
df[df['regex_label'].isnull()].head(5)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None

In [64]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1910, 7)

In [65]:
df_legacy = df_non_regex[df_non_regex.source=="LegacyCRM"]
df_legacy

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,llm,24,None
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,llm,48,None
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,llm,62,None
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,llm,105,None
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,llm,118,None
1826,2025-01-23 10:33:36,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,llm,122,None
2217,2025-05-12 09:46:54,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,llm,133,None

In [66]:
df_non_legacy = df_non_regex[df_non_regex.source!="LegacyCRM"]
df_non_legacy

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,None

In [67]:
df_non_legacy.shape

(1903, 7)

In [68]:
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [69]:
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
embeddings_filtered = model.encode(df_non_legacy['log_message'].tolist())

In [70]:
embeddings_filtered[:2]

array([[-1.02939606e-01,  3.35459374e-02, -2.20260937e-02,
         1.55100855e-03, -9.86921787e-03, -1.78956255e-01,
        -6.34410232e-02, -6.01761639e-02,  2.81108860e-02,
         5.99620752e-02, -1.72618274e-02,  1.43366132e-03,
        -1.49560049e-01,  3.15285614e-03, -5.66030480e-02,
         2.71685775e-02, -1.49890156e-02, -3.54037620e-02,
        -3.62936258e-02, -1.45410225e-02, -5.61492098e-03,
         8.75538662e-02,  4.55120578e-02,  2.50963848e-02,
         1.00187818e-02,  1.24267004e-02, -1.39923587e-01,
         7.68696219e-02,  3.14095207e-02, -4.15248610e-03,
         4.36902791e-02,  1.71249807e-02, -8.00951272e-02,
         5.74006326e-02,  1.89091973e-02,  8.55262429e-02,
         3.96398567e-02, -1.34371817e-01, -1.44363218e-03,
         3.06705455e-03,  1.76854059e-01,  4.44888510e-03,
        -1.69274826e-02,  2.24266183e-02, -4.35049944e-02,
         6.09031692e-03, -9.98169556e-03, -6.23973459e-02,
         1.07372459e-02, -6.04899786e-03, -7.14661106e-02,
        -8.45800061e-03, -3.18019427e-02, -1.00518361e-01,
         2.25882541e-04, -1.89341921e-02, -3.17794010e-02,
         4.00861576e-02,  2.19177920e-02, -2.59528477e-02,
         5.84525019e-02, -8.12510177e-02,  2.12028995e-02,
        -5.02687655e-02,  1.32056912e-02,  1.32677518e-03,
         2.27062646e-02, -3.45794186e-02,  3.91546823e-02,
        -2.09433623e-02,  3.24818771e-03,  4.43961285e-02,
        -9.85358432e-02, -2.88894996e-02, -6.85024261e-03,
         5.38818911e-02,  6.46110401e-02, -2.45060436e-02,
         9.21828672e-02, -7.49868676e-02,  1.23995030e-02,
        -1.00026570e-01, -4.64910530e-02,  6.01569973e-02,
        -2.46480703e-02, -7.08075464e-02, -2.77270637e-02,
         9.72611532e-02,  3.85840982e-02, -1.44293401e-02,
        -7.46890379e-04, -1.04305055e-02, -1.61843039e-02,
         4.43627723e-02,  9.25996620e-03,  7.14165270e-02,
         6.37917519e-02,  4.94931266e-02, -6.02567531e-02,
         4.04805429e-02, -3.42860557e-02, -1.93881467e-02,
         6.61233589e-02,  6.01589382e-02,  1.09371496e-02,
        -5.38630551e-03,  1.44580072e-02,  9.25429985e-02,
        -3.14563885e-02, -1.84351727e-02,  9.91874188e-03,
        -1.85574871e-02,  1.31278322e-03,  2.26764751e-05,
         2.02735094e-03,  2.75256429e-02, -4.81927842e-02,
         5.42825870e-02, -7.32067004e-02,  4.88667376e-02,
         4.98490259e-02, -9.01145488e-03, -4.68905680e-02,
        -4.25887071e-02, -8.19524005e-02,  3.87105718e-02,
         7.85504207e-02,  1.46077023e-32,  1.66706257e-02,
         5.25494255e-02, -1.82449110e-02, -1.26686450e-02,
         6.52837679e-02, -2.11777277e-02, -4.06322815e-02,
         4.14947197e-02, -2.48360913e-02, -1.33068133e-02,
        -5.46753593e-02, -5.99179708e-04, -4.89247683e-03,
        -6.27359226e-02, -3.84878218e-02, -6.13543466e-02,
         8.27405453e-02,  2.34379955e-02, -8.63087270e-03,
         1.31002627e-02,  6.44214749e-02, -4.41361852e-02,
        -6.98633343e-02, -7.36059919e-02, -4.33264300e-02,
         6.96519669e-03, -5.05956374e-02, -1.60911772e-02,
        -5.66794612e-02,  3.35451611e-03,  5.34115359e-02,
         2.47761384e-02, -1.47986021e-02, -2.93242913e-02,
         7.30228275e-02, -1.86833814e-02,  8.13137144e-02,
        -2.69967206e-02, -5.68056591e-02, -6.59388453e-02,
        -5.95391029e-03,  2.85312887e-02, -7.85358027e-02,
        -2.76692049e-03, -3.26466095e-03, -9.28333029e-02,
        -7.27363080e-02, -3.31903435e-02,  1.01411082e-01,
         9.79882404e-02, -9.78740528e-02,  1.98667850e-02,
         2.38837376e-02, -1.81672685e-02, -3.73708792e-02,
         1.96551136e-03,  6.34425730e-02,  1.18271234e-02,
        -1.12041393e-02, -3.87316719e-02,  9.32424515e-02,
         4.26629744e-03, -1.66872386e-02, -6.87464774e-02,
         1.55120241e-02, -4.97755669e-02,  3.34492885e-02,
         8.00032765e-02,  2.12282576e-02,  1.34581864e-01,
        -2.30729841e-02,  5.53858392e-02,  3.07557974e-02,
        -2.93905269e-02,  2.31905319e-02, -9.34308022e-02,
         7.58034810e-02, -5.21208020e-03, -5.14522865e-02,
         3.32689211e-02,  3.67963202e-02, -1.06450152e-02,
         1.01635084e-02, -2.07650922e-02, -5.85519187e-02,
         4.79328297e-02,  2.13694740e-02,  8.76213685e-02,
         3.35496757e-03, -3.80336940e-02, -1.81204919e-02,
         6.87449193e-03,  5.15879877e-02, -4.75598760e-02,
        -6.12065010e-02, -1.45483560e-32,  4.12804959e-03,
         4.59640520e-03, -5.63900881e-02,  4.32468811e-03,
        -1.09435222e-03,  9.31952335e-03, -2.20269114e-02,
         5.79564795e-02, -1.44787673e-02,  4.64155860e-02,
         1.43542901e-01, -6.89756647e-02,  6.09631799e-02,
        -8.93744081e-02,  2.40919348e-02,  2.06010677e-02,
        -2.82415655e-02, -6.48315474e-02,  5.64795323e-02,
        -7.48340553e-03, -3.52058373e-02,  8.51060450e-02,
         1.30359763e-02,  2.02257913e-02, -1.44391265e-02,
        -4.63718697e-02,  1.77209694e-02,  1.59105454e-02,
        -9.51009393e-02, -3.54526863e-02,  2.08695922e-02,
         3.84390773e-03, -8.77917930e-02,  6.44575804e-02,
         1.44171044e-02,  3.84727353e-03,  4.70991731e-02,
         4.94661666e-02,  1.53862825e-02, -2.59578861e-02,
         9.10894126e-02,  1.83307696e-02, -5.89206256e-02,
         2.51992494e-02, -3.30374241e-02,  8.23344290e-02,
         1.74792279e-02,  6.48047328e-02, -1.19674327e-02,
        -3.31778191e-02,  3.00177485e-02,  3.54220495e-02,
        -1.39623806e-02,  6.69272393e-02,  3.87920141e-02,
         6.06916361e-02,  1.17958512e-03, -2.38786563e-02,
        -1.26930416e-01,  1.13846520e-02,  1.59290098e-02,
        -1.29426531e-02, -8.63247812e-02,  8.53667874e-03,
         6.03761561e-02,  1.51122063e-02, -1.19132414e-01,
         1.15234395e-02,  5.97089194e-02, -3.93345654e-02,
         1.55673036e-02,  1.04602259e-02, -4.72457223e-02,
        -2.59243269e-02,  9.98524204e-03,  3.07146348e-02,
        -7.14844540e-02,  6.98966580e-03, -1.55133205e-02,
         2.18864549e-02, -2.78146006e-02,  6.92733601e-02,
        -2.75904015e-02,  2.62429491e-02,  3.52562107e-02,
        -4.26419191e-02,  7.46298116e-04,  6.59866408e-02,
        -5.15105948e-02, -3.58434357e-02, -6.53437525e-03,
        -2.75857970e-02, -1.00125559e-01,  7.83326104e-02,
        -1.45798698e-02, -6.18457179e-08,  2.00325698e-02,
         6.59785122e-02, -2.04702709e-02,  1.64043959e-02,
         7.63001665e-02,  7.32182860e-02,  5.65786147e-03,
        -6.97740645e-04, -3.63794086e-03,  6.02394082e-02,
        -3.27187479e-02, -6.45837933e-02, -5.97952567e-02,
        -1.76695660e-02,  6.10143412e-03, -5.63493511e-03,
        -1.22972220e-01,  6.35818988e-02, -2.19431818e-02,
        -1.16406448e-01,  2.34365761e-02, -7.23525882e-02,
         2.31773648e-02, -6.55987933e-02, -7.42681995e-02,
         2.60145776e-02,  3.59758660e-02,  7.68432915e-02,
        -3.08057163e-02, -2.34793741e-02, -6.30425960e-02,
        -3.62158157e-02, -1.03560509e-02, -4.75602932e-02,
        -2.87521724e-02,  2.96400581e-02, -5.26897609e-03,
         5.67889474e-02, -3.74489278e-03,  3.09612639e-02,
         3.48227471e-02,  3.78607847e-02,  2.10156087e-02,
         2.70691514e-02,  5.25520518e-02,  7.16229156e-02,
        -5.53752715e-03,  4.01093923e-02,  5.16276471e-02,
        -2.67314184e-02,  5.94224446e-02, -4.29223999e-02,
        -1.19760679e-02,  3.05985045e-02, -7.40331262e-02,
         1.84222274e-02, -8.64861161e-03, -8.83557573e-02,
        -5.91984391e-02, -1.00913552e-04,  1.12913616e-01,
         4.57793241e-03, -4.25971858e-02,  3.22621618e-03],
       [ 8.04575812e-03, -3.57392393e-02,  4.93873991e-02,
        -7.19184754e-03,  6.17651618e-04, -9.05685201e-02,
         5.75595051e-02, -4.39446270e-02,  1.74751580e-02,
         5.21203019e-02, -4.62331995e-02,  2.49039568e-02,
         4.80811670e-02,  6.86636269e-02,  3.56146730e-02,
         3.00088990e-02,  2.61449497e-02, -9.05241147e-02,
        -8.02174211e-02,  5.04851341e-02, -7.90870339e-02,
        -1.76856003e-03, -2.48927195e-02,  9.02152658e-02,
         5.83698135e-03, -6.91071004e-02, -6.67965412e-02,
        -6.99114799e-03, -1.04566015e-01, -2.66473703e-02,
         3.05639841e-02,  2.02934872e-02,  2.25454699e-02,
        -4.22683638e-03,  1.11173037e-02,  6.78260326e-02,
         1.06073162e-02,  7.56636485e-02, -8.22777748e-02,
         8.45729839e-03, -6.97612390e-02, -4.21974510e-02,
        -1.05674854e-02,  2.23673303e-02,  5.64496368e-02,
         8.16500001e-03,  1.09344065e-01,  3.16564813e-02,
        -1.76923815e-02, -3.21071297e-02, -3.39976065e-02,
        -4.91793093e-04,  3.72873619e-03,  2.83771660e-02,
        -1.28521854e-02, -1.07930985e-03, -6.32418916e-02,
         6.89900592e-02,  1.77270602e-02, -5.20959944e-02,
         8.28305446e-03,  5.45032807e-02, -5.42099848e-02,
        -4.53332812e-02, -4.07494083e-02, -2.82698367e-02,
         1.23606166e-02, -2.13815887e-02, -2.36265399e-02,
         1.25317685e-02, -2.37170607e-02,  3.97411510e-02,
        -1.24362282e-01,  7.60625526e-02,  5.50833717e-02,
         8.28216895e-02,  2.97118556e-02, -1.84067152e-02,
        -1.96194742e-02,  5.54319322e-02, -3.49144638e-02,
        -4.14677896e-02, -3.37047204e-02,  7.31324404e-02,
         4.41836901e-02,  2.55246609e-02, -8.26401450e-03,
        -1.07322894e-02, -4.26243842e-02, -2.84964032e-03,
         7.38559142e-02,  2.27767900e-02,  7.15389382e-04,
         4.36012447e-02,  5.09079359e-02,  6.38482645e-02,
        -2.73155645e-02, -6.55020922e-02, -7.69265220e-02,
         3.55171189e-02,  9.60493684e-02,  2.18195505e-02,
         1.20154889e-02, -1.17863603e-02, -4.57926746e-03,
        -8.58033262e-03,  3.37150618e-02,  2.31917668e-02,
        -7.58325383e-02, -5.23879342e-02,  4.53934111e-02,
        -3.80785801e-02, -3.34904902e-02,  9.20353234e-02,
         2.87689082e-02, -3.33817154e-02, -1.95854343e-03,
        -3.04540648e-04, -1.70499068e-02,  2.85335705e-02,
        -8.81096572e-02, -4.02253270e-02, -4.00092900e-02,
        -1.03193223e-02, -2.51968391e-02,  2.14093458e-02,
         1.31045192e-01, -5.29632709e-34, -1.09651707e-01,
         1.29811335e-02,  5.92654804e-03,  4.73506115e-02,
        -8.60298239e-03, -3.67089398e-02,  3.05214990e-02,
         5.53066917e-02, -4.71985638e-02, -1.25118773e-02,
        -1.15366407e-01,  9.07999370e-03,  1.07346483e-01,
        -4.94734980e-02, -1.34290028e-02, -4.61563021e-02,
         2.45320760e-02,  9.45077743e-03,  2.04324052e-02,
        -3.99918333e-02, -4.67825681e-02,  2.21171826e-02,
        -4.58187163e-02, -8.13274737e-03, -7.65672280e-03,
         1.92284267e-02,  4.85844910e-02, -2.55903080e-02,
         1.61539565e-03, -1.37180267e-02,  9.67307016e-03,
         7.36415526e-03,  1.14088152e-02,  1.28853410e-01,
         7.71836098e-03,  7.06362650e-02,  2.54451875e-02,
         4.06523757e-02,  2.44039726e-02,  1.43776918e-02,
        -6.00932725e-02,  7.38180205e-02, -2.44701076e-02,
         8.98901448e-02,  3.17050260e-03,  1.01834454e-01,
         4.17742133e-02, -5.95177747e-02, -3.23181972e-02,
         3.80938724e-02,  1.21155782e-02, -4.07833904e-02,
         2.84823552e-02,  4.90988605e-02, -9.35704075e-03,
         6.50074109e-02,  7.23532438e-02, -1.67793464e-02,
        -8.22415762e-03, -1.61573086e-02,  5.96225411e-02,
        -3.36083658e-02,  2.12108325e-02, -6.06090650e-02,
         1.54377654e-01, -7.24146068e-02, -3.77271771e-02,
        -3.26890051e-02, -1.80384354e-03, -1.01960385e-02,
        -1.60676800e-03, -6.91846535e-02,  8.28444958e-02,
         9.88839567e-02,  3.45465518e-03, -9.90247577e-02,
        -3.52827311e-02, -7.13178590e-02, -4.96000387e-02,
        -3.43954377e-02, -8.13042149e-02,  4.81447987e-02,
         5.00680599e-03, -2.21499670e-02, -5.60057163e-02,
         1.00067193e-02, -3.59794199e-02,  1.06184304e-01,
        -4.54196632e-02,  7.16393366e-02, -2.36773137e-02,
         9.98141989e-03,  2.73602139e-02,  1.05985448e-01,
         4.60163765e-02,  9.59028168e-34, -1.12306990e-01,
         2.78912354e-02, -3.35900784e-02,  5.39242551e-02,
        -2.22291779e-02,  1.53769329e-02,  3.10411528e-02,
         3.39010768e-02,  7.43166953e-02,  3.42470929e-02,
        -3.35052982e-03, -2.05350835e-02, -3.62370126e-02,
         2.29334179e-02, -3.01991757e-02, -1.00819923e-01,
         3.29194367e-02,  6.77542910e-02,  1.35645280e-02,
        -5.20548970e-03, -6.58158734e-02,  9.54550579e-02,
        -1.34039344e-02,  1.53885446e-02, -7.22936168e-02,
         9.67835933e-02, -8.08119923e-02, -4.53449693e-03,
        -6.42011240e-02, -4.99278605e-02,  4.64197583e-02,
         2.21341103e-02,  3.13109383e-02,  9.13568512e-02,
        -4.61120121e-02, -1.02761172e-01,  3.04415841e-02,
         5.09876087e-02,  6.70141354e-02,  1.04043614e-02,
         1.63533688e-02,  3.92031111e-02,  2.17154138e-02,
         5.36603890e-02,  3.62809375e-02, -4.22140621e-02,
        -2.47226804e-02,  1.90311763e-02,  3.61724086e-02,
         6.37020841e-02, -3.21579422e-03, -8.50389432e-03,
         3.94655727e-02,  9.02654137e-03,  1.93095822e-02,
         6.60718232e-02,  1.02694593e-02, -4.43853550e-02,
        -1.56522933e-02, -1.55714387e-02,  1.32904239e-02,
        -1.16108675e-02,  4.21832129e-02, -5.44776730e-02,
         1.29237190e-01, -2.25756783e-02,  5.26203737e-02,
        -1.58436745e-02,  9.33164954e-02,  6.38022739e-03,
        -9.36162099e-03, -6.08876199e-02, -3.27307805e-02,
        -3.44817117e-02,  3.29974107e-02, -4.79391627e-02,
        -9.81301144e-02,  2.91164760e-02, -2.70903297e-02,
         1.81866679e-02, -1.73860546e-02, -4.40371521e-02,
        -7.97002539e-02,  3.01647484e-02, -6.35260865e-02,
         1.25963334e-02,  8.50250050e-02, -4.58910577e-02,
         5.81017211e-02, -2.71001905e-02,  8.42775926e-02,
        -4.09972854e-02, -3.37655954e-02,  1.02088656e-02,
        -2.54193675e-02, -1.40610297e-08,  4.94446903e-02,
        -9.04356539e-02, -6.06710054e-02,  8.29529613e-02,
        -3.29032242e-02,  4.14910428e-02,  9.99591872e-03,
         6.96136896e-03,  3.99234798e-03, -3.24333347e-02,
        -3.14656943e-02, -5.33161834e-02, -3.80913652e-02,
         1.62077062e-02,  2.45778505e-02, -7.26419687e-02,
        -6.56893775e-02, -8.23131725e-02, -8.00501108e-02,
        -5.36648892e-02,  5.60894571e-02, -1.10913273e-02,
         9.62167047e-04, -1.22690305e-01, -5.13836518e-02,
         9.96702630e-03,  1.00696487e-02,  1.07073046e-01,
         1.19758267e-02,  1.00423861e-02, -6.28261864e-02,
        -7.49697313e-02, -6.34074537e-03, -2.72201467e-02,
        -1.28096148e-01, -2.62460150e-02, -1.81463789e-02,
        -9.85360071e-02, -3.02990433e-02, -4.02614884e-02,
         9.94290933e-02,  5.35999425e-02,  2.74899751e-02,
        -5.53678814e-03,  8.43571350e-02,  8.35161805e-02,
         3.74304876e-02,  7.11937472e-02,  2.98902933e-02,
         2.32728627e-02, -3.62112001e-02,  6.20540231e-02,
         2.15148423e-02,  5.19732647e-02,  1.45338289e-02,
        -4.60966155e-02,  5.02554439e-02, -7.27027282e-02,
         2.92779002e-02,  5.62663190e-02, -3.86354923e-02,
         1.53831802e-02, -6.23094663e-02, -2.77466476e-02]], dtype=float32)

In [71]:
len(embeddings_filtered)

1903

In [72]:
X = embeddings_filtered
y = df_non_legacy['target_label'].values

In [73]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [74]:
import joblib
joblib.dump(clf, '../models/log_classifier.joblib')

['../models/log_classifier.joblib']